site_name: Abdur's Notes
theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico

  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://arkalim.org
  analytics:
    provider: google
    property: G-XXXXXXXXXX

  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abdurrahmankalim
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/AbdurRahmanKalim
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/abdur.rahman.kalim

copyright: Copyright &copy; 2022 Abdur Rahman
