name: Obsidian Publish
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Publish obsidian
        uses: project-cool/obsidian-publish-action@main
        with:
          websiteId: "d9fed889-911e-4408-95da-45825e92cdb9"
          log_level: "info"
          token: ${{ secrets.NETLIFY_TOKEN }}